// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: changes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAttributeChange = `-- name: InsertAttributeChange :exec
INSERT INTO AttributeChanges (
    change_id,
    object_id,
    attribute_name,
    old_value,
    new_value,
    version_id,
    timestamp
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAttributeChangeParams struct {
	ChangeID      pgtype.UUID      `json:"change_id"`
	ObjectID      pgtype.UUID      `json:"object_id"`
	AttributeName string           `json:"attribute_name"`
	OldValue      []byte           `json:"old_value"`
	NewValue      []byte           `json:"new_value"`
	VersionID     pgtype.UUID      `json:"version_id"`
	Timestamp     pgtype.Timestamp `json:"timestamp"`
}

func (q *Queries) InsertAttributeChange(ctx context.Context, arg InsertAttributeChangeParams) error {
	_, err := q.db.Exec(ctx, insertAttributeChange,
		arg.ChangeID,
		arg.ObjectID,
		arg.AttributeName,
		arg.OldValue,
		arg.NewValue,
		arg.VersionID,
		arg.Timestamp,
	)
	return err
}
