// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: changes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAttributeChange = `-- name: InsertAttributeChange :exec
INSERT INTO AttributeChanges (
    object_id,
    usn_changed,
    attribute_schema_id,
    old_value,
    new_value,
    timestamp
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAttributeChangeParams struct {
	ObjectID          pgtype.UUID      `json:"object_id"`
	UsnChanged        int64            `json:"usn_changed"`
	AttributeSchemaID pgtype.UUID      `json:"attribute_schema_id"`
	OldValue          []byte           `json:"old_value"`
	NewValue          []byte           `json:"new_value"`
	Timestamp         pgtype.Timestamp `json:"timestamp"`
}

func (q *Queries) InsertAttributeChange(ctx context.Context, arg InsertAttributeChangeParams) error {
	_, err := q.db.Exec(ctx, insertAttributeChange,
		arg.ObjectID,
		arg.UsnChanged,
		arg.AttributeSchemaID,
		arg.OldValue,
		arg.NewValue,
		arg.Timestamp,
	)
	return err
}
