// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: domains.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDomain = `-- name: InsertDomain :exec
INSERT INTO Domains (domain_id, domain_name, domain_controller, highest_usn, current_usn)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (domain_id) DO NOTHING
`

type InsertDomainParams struct {
	DomainID         pgtype.UUID `json:"domain_id"`
	DomainName       string      `json:"domain_name"`
	DomainController string      `json:"domain_controller"`
	HighestUsn       pgtype.Int8 `json:"highest_usn"`
	CurrentUsn       pgtype.Int8 `json:"current_usn"`
}

func (q *Queries) InsertDomain(ctx context.Context, arg InsertDomainParams) error {
	_, err := q.db.Exec(ctx, insertDomain,
		arg.DomainID,
		arg.DomainName,
		arg.DomainController,
		arg.HighestUsn,
		arg.CurrentUsn,
	)
	return err
}
