// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attributechange struct {
	ObjectID          pgtype.UUID      `json:"object_id"`
	UsnChanged        int64            `json:"usn_changed"`
	AttributeSchemaID pgtype.UUID      `json:"attribute_schema_id"`
	OldValue          []byte           `json:"old_value"`
	NewValue          []byte           `json:"new_value"`
	Timestamp         pgtype.Timestamp `json:"timestamp"`
}

type Attributeschema struct {
	ObjectGuid      pgtype.UUID `json:"object_guid"`
	DomainID        pgtype.UUID `json:"domain_id"`
	LdapDisplayName string      `json:"ldap_display_name"`
	AttributeName   string      `json:"attribute_name"`
	AttributeID     string      `json:"attribute_id"`
	AttributeSyntax string      `json:"attribute_syntax"`
	OmSyntax        string      `json:"om_syntax"`
	SyntaxName      pgtype.Text `json:"syntax_name"`
	IsSingleValued  bool        `json:"is_single_valued"`
}

type Domain struct {
	DomainID         pgtype.UUID `json:"domain_id"`
	DomainName       string      `json:"domain_name"`
	DomainController string      `json:"domain_controller"`
	CurrentUsn       pgtype.Int8 `json:"current_usn"`
	HighestUsn       pgtype.Int8 `json:"highest_usn"`
}

type Object struct {
	ObjectID          pgtype.UUID      `json:"object_id"`
	ObjectType        string           `json:"object_type"`
	Distinguishedname pgtype.Text      `json:"distinguishedname"`
	CurrentUsn        pgtype.Int8      `json:"current_usn"`
	DomainID          pgtype.UUID      `json:"domain_id"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
}

type Objectversion struct {
	ObjectID           pgtype.UUID      `json:"object_id"`
	UsnChanged         int64            `json:"usn_changed"`
	Timestamp          pgtype.Timestamp `json:"timestamp"`
	AttributesSnapshot []byte           `json:"attributes_snapshot"`
	ModifiedBy         pgtype.Text      `json:"modified_by"`
}
