// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attributechange struct {
	ChangeID      pgtype.UUID      `json:"change_id"`
	ObjectID      pgtype.UUID      `json:"object_id"`
	AttributeName string           `json:"attribute_name"`
	OldValue      []byte           `json:"old_value"`
	NewValue      []byte           `json:"new_value"`
	VersionID     pgtype.UUID      `json:"version_id"`
	Timestamp     pgtype.Timestamp `json:"timestamp"`
}

type Domain struct {
	DomainID         pgtype.UUID `json:"domain_id"`
	DomainName       string      `json:"domain_name"`
	SchemaMetadata   []byte      `json:"schema_metadata"`
	DomainController string      `json:"domain_controller"`
	CurrentUsn       pgtype.Int8 `json:"current_usn"`
	HighestUsn       pgtype.Int8 `json:"highest_usn"`
}

type Object struct {
	ObjectID          pgtype.UUID      `json:"object_id"`
	ObjectType        string           `json:"object_type"`
	Distinguishedname pgtype.Text      `json:"distinguishedname"`
	CurrentVersion    pgtype.UUID      `json:"current_version"`
	DomainID          pgtype.UUID      `json:"domain_id"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
}

type Objectversion struct {
	VersionID          pgtype.UUID      `json:"version_id"`
	ObjectID           pgtype.UUID      `json:"object_id"`
	Timestamp          pgtype.Timestamp `json:"timestamp"`
	AttributesSnapshot []byte           `json:"attributes_snapshot"`
	ModifiedBy         pgtype.Text      `json:"modified_by"`
}
