// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: objects.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateCurrentUSN = `-- name: UpdateCurrentUSN :exec
UPDATE Objects
SET current_usn = $1
WHERE object_id = $2
`

type UpdateCurrentUSNParams struct {
	CurrentUsn pgtype.Int8 `json:"current_usn"`
	ObjectID   pgtype.UUID `json:"object_id"`
}

func (q *Queries) UpdateCurrentUSN(ctx context.Context, arg UpdateCurrentUSNParams) error {
	_, err := q.db.Exec(ctx, updateCurrentUSN, arg.CurrentUsn, arg.ObjectID)
	return err
}

const upsertObject = `-- name: UpsertObject :one
INSERT INTO Objects (object_id, object_type, distinguishedName, domain_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (object_id)
DO UPDATE SET
    updated_at = NOW(),
    distinguishedName = EXCLUDED.distinguishedName,
    object_type = EXCLUDED.object_type
RETURNING current_usn
`

type UpsertObjectParams struct {
	ObjectID          pgtype.UUID `json:"object_id"`
	ObjectType        string      `json:"object_type"`
	Distinguishedname pgtype.Text `json:"distinguishedname"`
	DomainID          pgtype.UUID `json:"domain_id"`
}

func (q *Queries) UpsertObject(ctx context.Context, arg UpsertObjectParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, upsertObject,
		arg.ObjectID,
		arg.ObjectType,
		arg.Distinguishedname,
		arg.DomainID,
	)
	var current_usn pgtype.Int8
	err := row.Scan(&current_usn)
	return current_usn, err
}
