// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: objects.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateLastProcessedUSN = `-- name: UpdateLastProcessedUSN :exec
UPDATE Objects
SET last_processed_usn = $1
WHERE object_id = $2
`

type UpdateLastProcessedUSNParams struct {
	LastProcessedUsn pgtype.Int8 `json:"last_processed_usn"`
	ObjectID         pgtype.UUID `json:"object_id"`
}

func (q *Queries) UpdateLastProcessedUSN(ctx context.Context, arg UpdateLastProcessedUSNParams) error {
	_, err := q.db.Exec(ctx, updateLastProcessedUSN, arg.LastProcessedUsn, arg.ObjectID)
	return err
}

const upsertObject = `-- name: UpsertObject :one
INSERT INTO Objects (object_id, object_type, distinguishedName, domain_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (object_id)
DO UPDATE SET
    updated_at = NOW(),
    distinguishedName = EXCLUDED.distinguishedName,
    object_type = EXCLUDED.object_type
RETURNING last_processed_usn
`

type UpsertObjectParams struct {
	ObjectID          pgtype.UUID `json:"object_id"`
	ObjectType        string      `json:"object_type"`
	Distinguishedname pgtype.Text `json:"distinguishedname"`
	DomainID          pgtype.UUID `json:"domain_id"`
}

func (q *Queries) UpsertObject(ctx context.Context, arg UpsertObjectParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, upsertObject,
		arg.ObjectID,
		arg.ObjectType,
		arg.Distinguishedname,
		arg.DomainID,
	)
	var last_processed_usn pgtype.Int8
	err := row.Scan(&last_processed_usn)
	return last_processed_usn, err
}
