// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetAttributeSchemaByLDAPName(ctx context.Context, arg GetAttributeSchemaByLDAPNameParams) (pgtype.UUID, error)
	GetPreviousSnapshot(ctx context.Context, arg GetPreviousSnapshotParams) ([]byte, error)
	InsertAttributeChange(ctx context.Context, arg InsertAttributeChangeParams) error
	InsertDomain(ctx context.Context, arg InsertDomainParams) error
	InsertVersion(ctx context.Context, arg InsertVersionParams) error
	UpdateDomainHighestUSN(ctx context.Context, arg UpdateDomainHighestUSNParams) error
	UpdateDomainLastProcessedUSN(ctx context.Context, arg UpdateDomainLastProcessedUSNParams) error
	UpdateLastProcessedUSN(ctx context.Context, arg UpdateLastProcessedUSNParams) error
	UpsertAttributeSchema(ctx context.Context, arg UpsertAttributeSchemaParams) error
	UpsertObject(ctx context.Context, arg UpsertObjectParams) (pgtype.Int8, error)
}

var _ Querier = (*Queries)(nil)
