// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetPreviousSnapshot(ctx context.Context, versionID pgtype.UUID) ([]byte, error)
	InsertAttributeChange(ctx context.Context, arg InsertAttributeChangeParams) error
	InsertDomain(ctx context.Context, arg InsertDomainParams) error
	InsertVersion(ctx context.Context, arg InsertVersionParams) error
	UpdateCurrentVersion(ctx context.Context, arg UpdateCurrentVersionParams) error
	UpsertAttributeSchema(ctx context.Context, arg UpsertAttributeSchemaParams) error
	UpsertObject(ctx context.Context, arg UpsertObjectParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
