// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: schemas.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertAttributeSchema = `-- name: UpsertAttributeSchema :exec
INSERT INTO AttributeSchemas (
    object_guid, domain_id, ldap_display_name, attribute_name, attribute_id,
    attribute_syntax, om_syntax, syntax_name, is_single_valued
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (object_guid)
DO UPDATE SET
    domain_id = EXCLUDED.domain_id,
    ldap_display_name = EXCLUDED.ldap_display_name,
    attribute_name = EXCLUDED.attribute_name,
    attribute_id = EXCLUDED.attribute_id,
    attribute_syntax = EXCLUDED.attribute_syntax,
    om_syntax = EXCLUDED.om_syntax,
    syntax_name = EXCLUDED.syntax_name,
    is_single_valued = EXCLUDED.is_single_valued
`

type UpsertAttributeSchemaParams struct {
	ObjectGuid      pgtype.UUID `json:"object_guid"`
	DomainID        pgtype.UUID `json:"domain_id"`
	LdapDisplayName string      `json:"ldap_display_name"`
	AttributeName   string      `json:"attribute_name"`
	AttributeID     string      `json:"attribute_id"`
	AttributeSyntax string      `json:"attribute_syntax"`
	OmSyntax        string      `json:"om_syntax"`
	SyntaxName      pgtype.Text `json:"syntax_name"`
	IsSingleValued  bool        `json:"is_single_valued"`
}

func (q *Queries) UpsertAttributeSchema(ctx context.Context, arg UpsertAttributeSchemaParams) error {
	_, err := q.db.Exec(ctx, upsertAttributeSchema,
		arg.ObjectGuid,
		arg.DomainID,
		arg.LdapDisplayName,
		arg.AttributeName,
		arg.AttributeID,
		arg.AttributeSyntax,
		arg.OmSyntax,
		arg.SyntaxName,
		arg.IsSingleValued,
	)
	return err
}
