// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: versions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPreviousSnapshot = `-- name: GetPreviousSnapshot :one
SELECT attributes_snapshot
FROM ObjectVersions
WHERE version_id = $1
`

func (q *Queries) GetPreviousSnapshot(ctx context.Context, versionID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPreviousSnapshot, versionID)
	var attributes_snapshot []byte
	err := row.Scan(&attributes_snapshot)
	return attributes_snapshot, err
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO ObjectVersions (version_id, object_id, timestamp, attributes_snapshot, modified_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertVersionParams struct {
	VersionID          pgtype.UUID      `json:"version_id"`
	ObjectID           pgtype.UUID      `json:"object_id"`
	Timestamp          pgtype.Timestamp `json:"timestamp"`
	AttributesSnapshot []byte           `json:"attributes_snapshot"`
	ModifiedBy         pgtype.Text      `json:"modified_by"`
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) error {
	_, err := q.db.Exec(ctx, insertVersion,
		arg.VersionID,
		arg.ObjectID,
		arg.Timestamp,
		arg.AttributesSnapshot,
		arg.ModifiedBy,
	)
	return err
}
