// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: versions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPreviousSnapshot = `-- name: GetPreviousSnapshot :one
SELECT attributes_snapshot
FROM ObjectVersions
WHERE object_id = $1 AND usn_changed = $2
`

type GetPreviousSnapshotParams struct {
	ObjectID   pgtype.UUID `json:"object_id"`
	UsnChanged int64       `json:"usn_changed"`
}

func (q *Queries) GetPreviousSnapshot(ctx context.Context, arg GetPreviousSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPreviousSnapshot, arg.ObjectID, arg.UsnChanged)
	var attributes_snapshot []byte
	err := row.Scan(&attributes_snapshot)
	return attributes_snapshot, err
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO ObjectVersions (object_id, usn_changed, timestamp, attributes_snapshot, modified_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertVersionParams struct {
	ObjectID           pgtype.UUID      `json:"object_id"`
	UsnChanged         int64            `json:"usn_changed"`
	Timestamp          pgtype.Timestamp `json:"timestamp"`
	AttributesSnapshot []byte           `json:"attributes_snapshot"`
	ModifiedBy         pgtype.Text      `json:"modified_by"`
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) error {
	_, err := q.db.Exec(ctx, insertVersion,
		arg.ObjectID,
		arg.UsnChanged,
		arg.Timestamp,
		arg.AttributesSnapshot,
		arg.ModifiedBy,
	)
	return err
}
